services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"  # Mapeia a porta 3306 do contêiner para a porta 3307 do host
    expose:
      - "3306"
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
